import React, { useState } from 'react';
import {
  ShieldCheck,
  ShieldAlert,
  AlertTriangle,
  CheckCircle2,
  AlertOctagon,
  Info,
  ShieldX,
  ChevronRight,
  Cpu,
  Search,
  BadgeCheck,
  Flag,
  Download,
  Copy,
  Check,
  FileText,
  Eye,
  ListChecks
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface PredictionResultProps {
  result: AnalysisResult;
  onReset: () => void;
}

export const PredictionResult: React.FC<PredictionResultProps> = ({ result, onReset }) => {
  const [copiedReport, setCopiedReport] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'highlightedText' | 'checklist'>('overview');
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});

  const isFake = result.classification === 'FAKE';
  const originalText = result.originalInput?.jobDescription || '';

  const handleCopyReport = () => {
    const reportText = `=====================================================
AI FAKE JOB POSTING DETECTION AUDIT REPORT
=====================================================
Date & Time    : ${result.timestamp ? new Date(result.timestamp).toLocaleString() : new Date().toLocaleString()}
Job Title      : ${result.originalInput?.jobTitle || 'Not Specified'}
Company Name   : ${result.originalInput?.companyName || 'Not Specified'}
Salary Range   : ${result.originalInput?.salary || 'Not Specified'}
Source URL     : ${result.originalInput?.jobUrl || 'Not Specified'}

CLASSIFICATION VERDICT: ${result.classification === 'FAKE' ? '[ FAKE / FRAUDULENT JOB ]' : '[ REAL / LEGITIMATE JOB ]'}
Assessment     : ${result.explanation}
AI/ML Model    : ${result.modelUsed || 'AI/ML Natural Language Classifier'}

${isFake ? 'POTENTIAL WARNING SIGNS DETECTED:' : 'POSITIVE CHARACTERISTICS DETECTED:'}
${(isFake ? result.detectedWarningSigns : result.positiveIndicators)
  .map((item, idx) => `  ${idx + 1}. ${item}`)
  .join('\n')}

SAFETY RECOMMENDATIONS FOR CANDIDATE:
${result.safetyRecommendations.map((rec, idx) => `  - ${rec}`).join('\n')}

=====================================================
DISCLAIMER: AI predictions are based on natural language processing heuristics and models. Always perform independent verification directly on the official company careers website before submitting sensitive documents or payments.
=====================================================`;

    navigator.clipboard.writeText(reportText).then(() => {
      setCopiedReport(true);
      setTimeout(() => setCopiedReport(false), 2500);
    });
  };

  const handleDownloadReport = () => {
    const reportText = `# AI Fake Job Posting Detection - Security Audit Report

**Date:** ${result.timestamp ? new Date(result.timestamp).toLocaleString() : new Date().toLocaleString()}  
**Target Role:** ${result.originalInput?.jobTitle || 'Not Specified'}  
**Claimed Employer:** ${result.originalInput?.companyName || 'Not Specified'}  
**Stipend / Salary:** ${result.originalInput?.salary || 'Not Specified'}  
**URL:** ${result.originalInput?.jobUrl || 'Not Specified'}  

---

## Classification: **${result.classification} JOB**

> **Assessment:** ${result.explanation}  
> **Model Engine:** ${result.modelUsed || 'AI/ML Classifier'}  

---

### ${isFake ? 'Potential Warning Signs' : 'Positive Indicators'}
${(isFake ? result.detectedWarningSigns : result.positiveIndicators)
  .map((item) => `- ${item}`)
  .join('\n')}

### Safety Action Plan
${result.safetyRecommendations.map((rec) => `- [ ] ${rec}`).join('\n')}

---
*Generated by AI Fake Job Posting Detection System.*
`;

    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Job-Audit-Report-${(result.originalInput?.companyName || 'job').replace(/[^a-z0-9]/gi, '_')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const toggleCheck = (index: number) => {
    setCheckedItems((prev) => ({ ...prev, [index]: !prev[index] }));
  };

  // Render annotated text with keyword highlights
  const renderAnnotatedText = () => {
    if (!originalText) {
      return <p className="text-xs text-slate-500 dark:text-slate-400 italic">No job description text provided.</p>;
    }

    const phrases = result.highlightedPhrases || [];
    if (phrases.length === 0) {
      return (
        <div className="p-4 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 text-xs text-slate-800 dark:text-slate-300 font-mono whitespace-pre-wrap leading-relaxed">
          {originalText}
        </div>
      );
    }

    // Build regex pattern for all phrases
    const pattern = new RegExp(
      `(${phrases.map((p) => p.phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})`,
      'gi'
    );

    const parts = originalText.split(pattern);

    return (
      <div className="p-4 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 text-xs text-slate-800 dark:text-slate-300 font-mono whitespace-pre-wrap leading-relaxed space-y-2">
        {parts.map((part, index) => {
          const match = phrases.find((p) => p.phrase.toLowerCase() === part.toLowerCase());
          if (match) {
            const isSusp = match.type === 'suspicious';
            return (
              <mark
                key={index}
                className={`px-1.5 py-0.5 rounded font-semibold transition-all inline-flex items-center gap-1 ${
                  isSusp
                    ? 'bg-rose-100 text-rose-800 border border-rose-300 dark:bg-rose-500/30 dark:text-rose-200 dark:border-rose-500/50'
                    : 'bg-emerald-100 text-emerald-800 border border-emerald-300 dark:bg-emerald-500/30 dark:text-emerald-200 dark:border-emerald-500/50'
                }`}
                title={`${isSusp ? '⚠️ Suspicious signal' : '✅ Positive cue'}: ${match.reason}`}
              >
                <span>{part}</span>
                <span className="text-[10px] opacity-75 font-normal">[{match.reason}]</span>
              </mark>
            );
          }
          return <span key={index}>{part}</span>;
        })}
      </div>
    );
  };

  const checklistItems = isFake
    ? [
        'Confirm if the employer exists on official ministry/government business registers.',
        'Ensure the job opening is listed under the company official careers page (e.g. company.com/careers).',
        'Verify that the recruiter sent emails exclusively from the corporate domain, not @gmail.com or @yahoo.com.',
        'Refuse any request for registration fees, training charges, or security deposits.',
        'Do not share copies of national IDs, banking PINs, or OTPs over chat apps.'
      ]
    : [
        'Cross-check the job ID on the verified company website or LinkedIn page.',
        'Review the company employee profiles and recent reviews on Glassdoor/LinkedIn.',
        'Ensure interviews are conducted through formal corporate video links (Teams/Meet/Zoom) rather than text-only chat.',
        'Confirm written employment offer letters contain standard corporate signatures and HR contacts.'
      ];

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-3 duration-300" id="prediction-result-container">
      {/* Primary Classification Banner */}
      <div
        id="classification-main-card"
        className={`rounded-2xl p-6 sm:p-8 border shadow-lg transition-all ${
          isFake
            ? 'bg-gradient-to-br from-rose-50 via-white to-rose-50/50 border-rose-300 text-rose-950 shadow-rose-500/5 dark:from-rose-950/90 dark:via-slate-900 dark:to-slate-950 dark:border-rose-500/60 dark:text-white dark:shadow-rose-950/30'
            : 'bg-gradient-to-br from-emerald-50 via-white to-emerald-50/50 border-emerald-300 text-emerald-950 shadow-emerald-500/5 dark:from-emerald-950/90 dark:via-slate-900 dark:to-slate-950 dark:border-emerald-500/60 dark:text-white dark:shadow-emerald-950/30'
        }`}
      >
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="flex items-start space-x-4 sm:space-x-5">
            <div
              className={`w-16 h-16 sm:w-20 sm:h-20 rounded-2xl flex items-center justify-center shrink-0 shadow-md ${
                isFake
                  ? 'bg-rose-100 text-rose-600 border border-rose-300 ring-4 ring-rose-100 dark:bg-rose-500/20 dark:text-rose-400 dark:border-rose-500/40 dark:shadow-rose-500/10 dark:ring-rose-500/10'
                  : 'bg-emerald-100 text-emerald-600 border border-emerald-300 ring-4 ring-emerald-100 dark:bg-emerald-500/20 dark:text-emerald-400 dark:border-emerald-500/40 dark:shadow-emerald-500/10 dark:ring-emerald-500/10'
              }`}
            >
              {isFake ? (
                <ShieldAlert className="w-9 h-9 sm:w-11 sm:h-11" />
              ) : (
                <ShieldCheck className="w-9 h-9 sm:w-11 sm:h-11" />
              )}
            </div>

            <div className="space-y-1.5">
              <div className="flex items-center space-x-2 flex-wrap gap-y-1">
                <span
                  className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold tracking-wider uppercase border ${
                    isFake
                      ? 'bg-rose-100 text-rose-800 border-rose-300 dark:bg-rose-500/30 dark:text-rose-200 dark:border-rose-400/50'
                      : 'bg-emerald-100 text-emerald-800 border-emerald-300 dark:bg-emerald-500/30 dark:text-emerald-200 dark:border-emerald-400/50'
                  }`}
                >
                  {isFake ? 'Potential Fraud Alert' : 'Verified Legitimacy Patterns'}
                </span>
                <span className="text-xs text-slate-500 dark:text-slate-400 font-mono">
                  {result.modelUsed || 'AI/ML Classifier'}
                </span>
              </div>

              {/* Classification Label */}
              <h3 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
                {isFake ? (
                  <span className="text-rose-600 dark:text-rose-400">FAKE JOB</span>
                ) : (
                  <span className="text-emerald-600 dark:text-emerald-400">REAL JOB</span>
                )}
              </h3>

              {/* Classification Assessment Sentence */}
              <p className="text-sm sm:text-base text-slate-700 dark:text-slate-200 leading-relaxed max-w-2xl font-medium">
                {result.explanation}
              </p>
            </div>
          </div>

          {/* Action Bar (Export Report & Retest) */}
          <div className="shrink-0 flex sm:flex-col justify-end items-end gap-2">
            <div className="flex items-center space-x-2">
              <button
                type="button"
                id="btn-copy-audit-report"
                onClick={handleCopyReport}
                className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 dark:bg-slate-800 dark:hover:bg-slate-700 dark:text-white text-xs font-semibold border border-slate-300 dark:border-slate-700 transition-colors flex items-center space-x-1.5 cursor-pointer shadow-xs"
                title="Copy full security report"
              >
                {copiedReport ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                    <span>Copied Report!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-slate-600 dark:text-slate-300" />
                    <span>Copy Report</span>
                  </>
                )}
              </button>

              <button
                type="button"
                id="btn-download-audit-report"
                onClick={handleDownloadReport}
                className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold transition-colors flex items-center space-x-1.5 shadow-sm shadow-indigo-600/20 cursor-pointer"
                title="Download report as Markdown file"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export .MD</span>
              </button>
            </div>

            <button
              id="btn-retest-job"
              onClick={onReset}
              className="px-3.5 py-2 rounded-xl bg-slate-200/80 hover:bg-slate-300 text-slate-800 dark:bg-white/10 dark:hover:bg-white/20 dark:text-white text-xs font-semibold backdrop-blur-sm border border-slate-300 dark:border-white/20 transition-colors cursor-pointer"
            >
              Analyze Another Job
            </button>
          </div>
        </div>
      </div>

      {/* Sub-view Navigation Pills */}
      <div className="flex items-center space-x-2 border-b border-slate-200 dark:border-slate-800 pb-2">
        <button
          type="button"
          onClick={() => setActiveTab('overview')}
          className={`flex items-center space-x-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-colors cursor-pointer ${
            activeTab === 'overview'
              ? 'bg-slate-200 text-slate-900 dark:bg-slate-800 dark:text-white border border-slate-300 dark:border-slate-700'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100 dark:text-slate-400 dark:hover:text-white dark:hover:bg-slate-900'
          }`}
        >
          <FileText className="w-3.5 h-3.5" />
          <span>Analysis Overview</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('highlightedText')}
          className={`flex items-center space-x-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-colors cursor-pointer ${
            activeTab === 'highlightedText'
              ? 'bg-slate-200 text-slate-900 dark:bg-slate-800 dark:text-white border border-slate-300 dark:border-slate-700'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100 dark:text-slate-400 dark:hover:text-white dark:hover:bg-slate-900'
          }`}
        >
          <Eye className="w-3.5 h-3.5" />
          <span>Keyword Signals in Text</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('checklist')}
          className={`flex items-center space-x-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-colors cursor-pointer ${
            activeTab === 'checklist'
              ? 'bg-slate-200 text-slate-900 dark:bg-slate-800 dark:text-white border border-slate-300 dark:border-slate-700'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100 dark:text-slate-400 dark:hover:text-white dark:hover:bg-slate-900'
          }`}
        >
          <ListChecks className="w-3.5 h-3.5" />
          <span>Due Diligence Checklist</span>
        </button>
      </div>

      {/* Tab 1: Analysis Overview */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          {isFake ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Potential Warning Signs */}
              <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-rose-200 dark:border-rose-500/30 shadow-xs p-6 space-y-4" id="warning-signs-card">
                <div className="flex items-center space-x-2.5 text-rose-600 dark:text-rose-400 border-b border-slate-200 dark:border-slate-800 pb-3.5">
                  <div className="w-8 h-8 rounded-lg bg-rose-100 dark:bg-rose-500/20 flex items-center justify-center text-rose-600 dark:text-rose-400">
                    <AlertTriangle className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-base text-slate-900 dark:text-white">Potential Warning Signs</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Suspicious traits identified by the AI/ML classifier</p>
                  </div>
                </div>

                <ul className="space-y-2.5">
                  {result.detectedWarningSigns && result.detectedWarningSigns.length > 0 ? (
                    result.detectedWarningSigns.map((sign, idx) => (
                      <li key={idx} className="flex items-start space-x-2.5 text-xs sm:text-sm text-rose-900 dark:text-rose-200 bg-rose-50 dark:bg-rose-950/30 p-2.5 rounded-xl border border-rose-200 dark:border-rose-500/20">
                        <AlertOctagon className="w-4 h-4 text-rose-500 dark:text-rose-400 shrink-0 mt-0.5" />
                        <span className="font-medium">{sign}</span>
                      </li>
                    ))
                  ) : (
                    <li className="flex items-start space-x-2 text-sm text-rose-700 dark:text-rose-300">
                      <AlertOctagon className="w-4 h-4 text-rose-500 dark:text-rose-400 shrink-0 mt-0.5" />
                      <span>Unrealistic earning claims or suspicious unverified recruitment patterns detected.</span>
                    </li>
                  )}
                </ul>
              </div>

              {/* Safety Recommendations */}
              <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-amber-200 dark:border-amber-500/30 shadow-xs p-6 space-y-4" id="safety-recommendations-card">
                <div className="flex items-center space-x-2.5 text-amber-600 dark:text-amber-400 border-b border-slate-200 dark:border-slate-800 pb-3.5">
                  <div className="w-8 h-8 rounded-lg bg-amber-100 dark:bg-amber-500/20 flex items-center justify-center text-amber-600 dark:text-amber-400">
                    <ShieldX className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-base text-slate-900 dark:text-white">Safety Recommendations</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Protect yourself from potential recruitment scams</p>
                  </div>
                </div>

                <ul className="space-y-2.5">
                  {result.safetyRecommendations && result.safetyRecommendations.length > 0 ? (
                    result.safetyRecommendations.map((rec, idx) => (
                      <li key={idx} className="flex items-start space-x-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-950 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800">
                        <ChevronRight className="w-4 h-4 text-amber-500 dark:text-amber-400 shrink-0 mt-0.5" />
                        <span>{rec}</span>
                      </li>
                    ))
                  ) : (
                    <>
                      <li className="flex items-start space-x-2 text-sm text-slate-700 dark:text-slate-300">
                        <ChevronRight className="w-4 h-4 text-amber-500 dark:text-amber-400 shrink-0 mt-0.5" />
                        <span>Do not pay money to obtain a job or purchase mandatory kits.</span>
                      </li>
                      <li className="flex items-start space-x-2 text-sm text-slate-700 dark:text-slate-300">
                        <ChevronRight className="w-4 h-4 text-amber-500 dark:text-amber-400 shrink-0 mt-0.5" />
                        <span>Verify the company through its official website and careers page.</span>
                      </li>
                    </>
                  )}
                </ul>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Positive Characteristics */}
              <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-emerald-200 dark:border-emerald-500/30 shadow-xs p-6 space-y-4" id="positive-indicators-card">
                <div className="flex items-center space-x-2.5 text-emerald-600 dark:text-emerald-400 border-b border-slate-200 dark:border-slate-800 pb-3.5">
                  <div className="w-8 h-8 rounded-lg bg-emerald-100 dark:bg-emerald-500/20 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
                    <BadgeCheck className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="font-bold text-base text-slate-900 dark:text-white">Positive Characteristics Detected</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Legitimate structural and organizational indicators</p>
                  </div>
                </div>

                <ul className="space-y-2.5">
                  {result.positiveIndicators && result.positiveIndicators.length > 0 ? (
                    result.positiveIndicators.map((ind, idx) => (
                      <li key={idx} className="flex items-start space-x-2.5 text-xs sm:text-sm text-emerald-900 dark:text-emerald-200 bg-emerald-50 dark:bg-emerald-950/30 p-2.5 rounded-xl border border-emerald-200 dark:border-emerald-500/20">
                        <CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400 shrink-0 mt-0.5" />
                        <span className="font-medium">{ind}</span>
                      </li>
                    ))
                  ) : (
                    <>
                      <li className="flex items-start space-x-2 text-sm text-slate-700 dark:text-slate-300">
                        <CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400 shrink-0 mt-0.5" />
                        <span>Clear job responsibilities and structured role summary</span>
                      </li>
                      <li className="flex items-start space-x-2 text-sm text-slate-700 dark:text-slate-300">
                        <CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400 shrink-0 mt-0.5" />
                        <span>Relevant skills, qualifications, and educational criteria</span>
                      </li>
                    </>
                  )}
                </ul>
              </div>

              {/* Verification Best Practices */}
              <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs p-6 space-y-4" id="real-job-guidelines-card">
                <div className="flex items-center space-x-2.5 text-indigo-600 dark:text-indigo-400 border-b border-slate-200 dark:border-slate-800 pb-3.5">
                  <div className="w-8 h-8 rounded-lg bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                    <ShieldCheck className="w-4 h-4" />
                  </div>
                  <div>
                    <h4 className="font-bold text-base text-slate-900 dark:text-white">Verification Steps Before Applying</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Standard candidate due diligence</p>
                  </div>
                </div>

                <ul className="space-y-2.5">
                  <li className="flex items-start space-x-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-950 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800">
                    <ChevronRight className="w-4 h-4 text-indigo-500 dark:text-indigo-400 shrink-0 mt-0.5" />
                    <span>Verify that the vacancy is mirrored on the company's verified careers domain.</span>
                  </li>
                  <li className="flex items-start space-x-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-950 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800">
                    <ChevronRight className="w-4 h-4 text-indigo-500 dark:text-indigo-400 shrink-0 mt-0.5" />
                    <span>Ensure recruiters email you from corporate domains rather than generic webmail accounts.</span>
                  </li>
                  <li className="flex items-start space-x-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-950 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800">
                    <ChevronRight className="w-4 h-4 text-indigo-500 dark:text-indigo-400 shrink-0 mt-0.5" />
                    <span>Never transfer funds or purchase proprietary software licenses prior to official employment.</span>
                  </li>
                </ul>

                {/* AI Disclaimer */}
                <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-xl text-xs text-slate-600 dark:text-slate-400 flex items-start space-x-2 border border-slate-200 dark:border-slate-800">
                  <Info className="w-4 h-4 text-slate-400 shrink-0 mt-0.5" />
                  <span>
                    <strong className="text-slate-800 dark:text-slate-200">Notice:</strong> AI predictions are based on the information provided and do not guarantee that a job is legitimate.
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Tab 2: Keyword Signals in Text */}
      {activeTab === 'highlightedText' && (
        <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 space-y-4 animate-in fade-in duration-200 shadow-xs">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between pb-3 border-b border-slate-200 dark:border-slate-800 gap-2">
            <div>
              <h4 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Search className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
                <span>Text Linguistic Feature Highlighter</span>
              </h4>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Red badges indicate suspicious scam patterns; green badges indicate legitimate corporate structural elements.
              </p>
            </div>
            <div className="flex items-center space-x-3 text-xs">
              <span className="flex items-center gap-1 text-rose-700 dark:text-rose-300 font-medium">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500"></span> Suspicious Signal
              </span>
              <span className="flex items-center gap-1 text-emerald-700 dark:text-emerald-300 font-medium">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500"></span> Positive Indicator
              </span>
            </div>
          </div>

          {renderAnnotatedText()}
        </div>
      )}

      {/* Tab 3: Due Diligence Checklist */}
      {activeTab === 'checklist' && (
        <div className="bg-white dark:bg-slate-900/90 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 space-y-4 animate-in fade-in duration-200 shadow-xs">
          <div className="pb-3 border-b border-slate-200 dark:border-slate-800">
            <h4 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <ListChecks className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              <span>Candidate Due-Diligence Checklist</span>
            </h4>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Check off each verification step before sharing personal credentials or accepting offers.
            </p>
          </div>

          <div className="space-y-2.5">
            {checklistItems.map((item, idx) => (
              <label
                key={idx}
                className={`flex items-start space-x-3 p-3.5 rounded-xl border transition-all cursor-pointer ${
                  checkedItems[idx]
                    ? 'bg-indigo-50 border-indigo-200 text-indigo-900 dark:bg-indigo-950/30 dark:border-indigo-500/40 dark:text-slate-200'
                    : 'bg-slate-50 border-slate-200 text-slate-700 hover:border-slate-300 dark:bg-slate-950 dark:border-slate-800 dark:text-slate-300 dark:hover:border-slate-700'
                }`}
              >
                <input
                  type="checkbox"
                  checked={!!checkedItems[idx]}
                  onChange={() => toggleCheck(idx)}
                  className="w-4 h-4 rounded mt-0.5 text-indigo-600 focus:ring-indigo-500 bg-white dark:bg-slate-900 border-slate-300 dark:border-slate-700"
                />
                <span className={`text-xs sm:text-sm leading-relaxed ${checkedItems[idx] ? 'line-through text-slate-400' : ''}`}>
                  {item}
                </span>
              </label>
            ))}
          </div>
        </div>
      )}

      {/* AI/ML Feature Extraction Inspector Matrix */}
      <div className="bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 space-y-4 shadow-xs" id="ml-features-inspection-card">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800 gap-2">
          <div className="flex items-center space-x-2">
            <Cpu className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">AI/ML Feature Extraction Matrix</h4>
          </div>
          <span className="text-xs text-slate-600 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 px-2.5 py-1 rounded-md border border-slate-200 dark:border-slate-700">
            Model: {result.modelUsed || 'NLP Classifier'}
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="bg-slate-50 dark:bg-slate-950/70 p-3 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-xs text-slate-500 dark:text-slate-400 block">Urgency Vocabulary</span>
            <span className={`text-xs sm:text-sm font-semibold ${result.features?.linguisticUrgency === 'High' ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
              {result.features?.linguisticUrgency || (isFake ? 'High Urgency' : 'Low / Professional')}
            </span>
          </div>

          <div className="bg-slate-50 dark:bg-slate-950/70 p-3 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-xs text-slate-500 dark:text-slate-400 block">Upfront Fee Trigger</span>
            <span className={`text-xs sm:text-sm font-semibold ${result.features?.monetaryUpfrontRequirement ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
              {result.features?.monetaryUpfrontRequirement ? 'Detected (Red Flag)' : 'None Detected'}
            </span>
          </div>

          <div className="bg-slate-50 dark:bg-slate-950/70 p-3 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-xs text-slate-500 dark:text-slate-400 block">Scope Structure</span>
            <span className={`text-xs sm:text-sm font-semibold ${result.features?.structuredResponsibilities ? 'text-emerald-600 dark:text-emerald-400' : 'text-amber-600 dark:text-amber-400'}`}>
              {result.features?.structuredResponsibilities ? 'Well Defined' : 'Vague / Short'}
            </span>
          </div>

          <div className="bg-slate-50 dark:bg-slate-950/70 p-3 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1">
            <span className="text-xs text-slate-500 dark:text-slate-400 block">Contact Channel</span>
            <span className={`text-xs sm:text-sm font-semibold ${isFake ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
              {result.features?.communicationChannel || (isFake ? 'Informal/Chat' : 'Corporate/Portal')}
            </span>
          </div>
        </div>

        {/* Flagged Phrases */}
        {result.highlightedPhrases && result.highlightedPhrases.length > 0 && (
          <div className="pt-2 space-y-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-400 flex items-center gap-1.5">
              <Search className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" /> Detected Key Phrases & Signals:
            </span>
            <div className="flex flex-wrap gap-2">
              {result.highlightedPhrases.map((item, idx) => (
                <span
                  key={idx}
                  className={`inline-flex items-center space-x-1.5 text-xs px-2.5 py-1 rounded-lg border font-mono ${
                    item.type === 'suspicious'
                      ? 'bg-rose-50 border-rose-200 text-rose-800 dark:bg-rose-950/80 dark:border-rose-800 dark:text-rose-300'
                      : 'bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-emerald-950/80 dark:border-emerald-800 dark:text-emerald-300'
                  }`}
                  title={item.reason}
                >
                  <Flag className={`w-3 h-3 ${item.type === 'suspicious' ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`} />
                  <span>"{item.phrase}"</span>
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
